#!/bin/bash
#SBATCH --time=00:00:00
#SBATCH --account=cfang
source ~/env/bin/activate
module load singularity/3.4.2

singularity shell /home/campbell/cfang/pipecomp-singularity.sif
Rscript /home/cambpell/cfang/automl_scrna/scripts/Rscripts/randomForestFixedResCV.R
